name: jira_for_mobile
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  provider: any
  dio: any
  cached_network_image: any
  shared_preferences: any
  lottie: any
  webview_flutter: any

  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  assets:
    - assets/Images/
    - assets/Animation/jira.json

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500

  uses-material-design: true

